apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app: web
spec:
  selector:
    app: web
    tier: frontend
  type: NodePort
  ports:
    - nodePort: 31000
      port: 81
      targetPort: 80
  
---
    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pv-claim
  labels:
    app: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: webpod
  labels:
    app: web
spec:
  containers:
  - image: vimal13/apache-webserver-php
    name: webcon
    ports:
    - containerPort: 80
       name: webport
    volumeMounts:
    - name: web-persistent-volume 
      mountPath: /var/www/html
    volumes:
    - name: web-persistent-volume
      persistentVolumeClaim:
        claimName: web-pv-claim
